# most simple

try:
	foobar
except:
	print("Problem")

print("after the try")

# after that

# try:
# 	foobar
# except NameError as err:
# 	print(err)